### ISSUE TITLE
Class too short

### ISSUE THREAD

**Issue by ObstinateM** [ObstinateM/vt-plus-plus#1]
The class name is not showing properly when the class length is less than an hour.

Exemple : (l1portailmi_g1)
<img width="328" alt="image" src="https://user-images.githubusercontent.com/45576315/189305823-47e0431c-0782-48d8-9107-63cfc4cf81d7.png">

<img width="334" alt="image" src="https://user-images.githubusercontent.com/45576315/189306766-892bde9c-aed9-43fb-8422-f38501b99617.png">

**Comment by Logorrheique** [comment]
I'm going to work on ASAP 👍 
the idea being to reduce to the minimum readable

**Comment by ekazukii** [comment]
> I'm going to work on ASAP +1 the idea being to reduce to the minimum readable

Any updates ?

**Comment by ObstinateM** [comment]
> 

😁

**Comment by ObstinateM** [comment]
> I'm going to work on ASAP 👍 the idea being to reduce to the minimum readable

😁😁

**Comment by ekazukii** [comment]
> I'm going to work on ASAP 👍 
> 
> the idea being to reduce to the minimum readable 

GM, did you find the time to work on this ? @Logorrheique

**Comment by Logorrheique** [comment]
> > I'm going to work on ASAP 👍
> > the idea being to reduce to the minimum readable
> 
> GM, did you find the time to work on this ? @Logorrheique

Fixed

**Comment by ObstinateM** [comment]
> > > I'm going to work on ASAP 👍
> > > the idea being to reduce to the minimum readable
> > 
> > 
> > GM, did you find the time to work on this ? @Logorrheique
> 
> Fixed

I dont see any PR @Logorrheique

**Comment by ekazukii** [comment]
> > > > I'm going to work on ASAP 👍
> 
> > > > the idea being to reduce to the minimum readable
> 
> > > 
> 
> > > 
> 
> > > GM, did you find the time to work on this ? @Logorrheique
> 
> > 
> 
> > Fixed
> 
> 
> 
> I dont see any PR @Logorrheique 

Me neither, probably a problem on GitHub servers.

**Comment by Logorrheique** [comment]
> > > > I'm going to work on ASAP 👍
> > > > the idea being to reduce to the minimum readable
> > > 
> > > 
> > > GM, did you find the time to work on this ? @Logorrheique
> > 
> > 
> > Fixed
> 
> I dont see any PR @Logorrheique

I don't have the right to make a PR :(-

**Comment by Logorrheique** [comment]
![image](https://user-images.githubusercontent.com/60989517/210139627-ceb09731-7ea3-4579-9fdb-8630e5727f7a.png)

Seems Good !
