### ISSUE TITLE
Missing UE names (only codes for some UE)

### ISSUE THREAD

**Issue by samuelortion** [ObstinateM/vt-plus-plus#2]
Thanks for this project.

There are some UE names that are not displayed.

As already mentioned in the Info-Evry discord server; the .ics file from VT lacks these names.

I could maybe help to correct this issue, with UE code / UE name relation, if needed.

**Comment by ObstinateM** [comment]
Can you provide a code where these UE names are absent?

Feel free to open a pull request if you want to.

**Comment by samuelortion** [comment]
It happens mainly for Biology Portal's UE in the time table of DL bio-info (VT-code: `L3DLBI`).

**Comment by ObstinateM** [comment]
Alright, easy to fix. I'll fix it asap.

**Comment by samuelortion** [comment]
#3: Adds some of the biology UE names (I didn't achieve to display the proper UE names though; I surely missed something).

**Comment by ObstinateM** [comment]
Fixed #3

**Comment by samuelortion** [comment]
Thanks ;-)
